### ISSUE TITLE
hilariously ironic 

### ISSUE THREAD

**Issue by Innomen** [ageekhere/Definitive-Supreme-Commander-Launcher#11]
Downloaded this to try and set resolution because FAF apparently can't handle a wide screen. The bottom cuts off, so no launch buttons. And what happens when I launch this? Same thing XD What is with everyone writing their apps for phone resolutions or CRT squares? This is a courtesy feedback not asking for help. I'm abandoning the game.

**Comment by ageekhere** [comment]
Did you set the primary adapter to windowed mode?
![screenshot](https://github.com/ageekhere/Definitive-Supreme-Commander-Launcher/assets/13173133/9e5d2c26-1c87-49b0-8f6d-303eab459d1e)

**Comment by ageekhere** [comment]
This sounds like a limitation for Definitive Supreme, closing.
