### ISSUE TITLE
Clicking on Forged Alliance (Steam) just opens Supreme Commander (Steam), regardless of whether I have Supreme Commander installed or not or enabled inside the launcher or not.

### ISSUE THREAD

**Issue by Shimanim** [ageekhere/Definitive-Supreme-Commander-Launcher#8]
Clicking on Forged Alliance (Steam) just opens Supreme Commander (Steam), regardless of whether I have Supreme Commander installed or not or enabled inside the launcher or not.

**Comment by ageekhere** [comment]
I see the issue, i entered the wrong steam path, will work on a fix

**Comment by ageekhere** [comment]
@Shimanim Update is release

**Comment by ageekhere** [comment]
This issue should now be fixed
